# Generated by Django 6.0 on 2026-01-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_taskattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='original_test_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
