# Generated by Django 5.2.9 on 2026-01-06 12:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_task_original_test_id_alter_task_correct_answer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['subject', 'topic'], name='core_task_subject_bcc7bf_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['difficulty'], name='core_task_difficu_d939b6_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['order'], name='core_task_order_880fed_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['subject', 'order'], name='core_task_subject_69261c_idx'),
        ),
        migrations.AddIndex(
            model_name='taskattempt',
            index=models.Index(fields=['user', 'is_solved'], name='core_taskat_user_id_ba77f8_idx'),
        ),
        migrations.AddIndex(
            model_name='taskattempt',
            index=models.Index(fields=['user', 'task', 'is_solved'], name='core_taskat_user_id_bdc46a_idx'),
        ),
        migrations.AddIndex(
            model_name='taskattempt',
            index=models.Index(fields=['-updated_at'], name='core_taskat_updated_9acb79_idx'),
        ),
    ]
